# Manager service for discovery
apiVersion: v1
kind: Service
metadata:
  name: istio-manager
  labels:
    istio: manager
spec:
  ports:
  - port: 8080
    name: http-discovery
  selector:
    istio: manager
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-manager
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: ignore
      labels:
        istio: manager
    spec:
      containers:
      - name: manager
        image: docker.io/istio/runtime:2017-03-22-21.21.48
        imagePullPolicy: Always
        args: ["discovery", "-v", "2", "-m", "istio-mixer:9091"]
        ports:
        - containerPort: 8080
---
